<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class SaiyanSeeder extends Seeder
{
	public function run()
	{
		$this->db->query('TRUNCATE TABLE saiyan RESTART IDENTITY CASCADE');

		$data = [
			[
				'nom' => 'Lecarpentier',
				'prenom' => 'Luc',
				'mail' => 'luc.lecarpentier5@gmail.com',
				'mdp' => password_hash('#Motdepasse1', PASSWORD_DEFAULT),
				'adresse' => json_encode(['query' => '123 rue de Sport 75001 Paris']),
				'tel' => '0102030405',
				'sexe' => 'H',
				'admin' => true,
				'age' => 26,
				'taille' => 160,
				'poids' => 95,
				'reset_token' => null,
				'reset_token_expiration' => null,
			],
			[
				'nom' => 'Hay',
				'prenom' => 'Baptiste',
				'mail' => 'baptiste.hay@hotmail.fr',
				'mdp' => password_hash('Bapt!ste01', PASSWORD_DEFAULT),
				'adresse' => json_encode(['query' => '65 rue Casimir Delavigne 76600 Le Havre']),
				'tel' => '0640129938',
				'sexe' => 'H',
				'admin' => true,
				'age' => 21,
				'taille' => 178,
				'poids' => 72.8,
				'reset_token' => null,
				'reset_token_expiration' => null,
			],
			[
				'nom' => 'Dupont',
				'prenom' => 'Marie',
				'mail' => 'marie.dupont@gmail.com',
				'mdp' => password_hash('Mar!e123', PASSWORD_DEFAULT),
				'adresse' => json_encode(['query' => '789 boulevard Leningrad 76610 Le Havre']),
				'tel' => '0765432198',
				'sexe' => 'F',
				'admin' => false,
				'age' => 30,
				'taille' => 170,
				'poids' => 65,
				'reset_token' => null,
				'reset_token_expiration' => null,
			],
			[
				'nom' => 'Dubois',
				'prenom' => 'Claire',
				'mail' => 'claire.dubois@gmail.com',
				'mdp' => password_hash('ClaireDubo!s89', PASSWORD_DEFAULT),
				'adresse' => json_encode(['query' => '789 boulevard Leningrad 76610 Le Havre']),
				'tel' => '0723456789',
				'sexe' => 'F',
				'admin' => false,
				'age' => 42,
				'taille' => 160,
				'poids' => 55,
				'reset_token' => null,
				'reset_token_expiration' => null,
			],
			[
				'nom' => 'Martin',
				'prenom' => 'Jean',
				'mail' => 'jean.martin@gmail.com',
				'mdp' => password_hash('Je@nMartin2024', PASSWORD_DEFAULT),
				'adresse' => json_encode(['query' => '14 avenue des Champs 69003 Lyon']),
				'tel' => '0621349876',
				'sexe' => 'H',
				'admin' => false,
				'age' => 35,
				'taille' => 180,
				'poids' => 85,
				'reset_token' => null,
				'reset_token_expiration' => null,
			],
			[
				'nom' => 'Bernard',
				'prenom' => 'Sophie',
				'mail' => 'sophie.bernard@gmail.com',
				'mdp' => password_hash('SophieBernard@22', PASSWORD_DEFAULT),
				'adresse' => json_encode(['query' => '45 place de la Liberté 31000 Toulouse']),
				'tel' => '0756432198',
				'sexe' => 'F',
				'admin' => false,
				'age' => 28,
				'taille' => 165,
				'poids' => 60,
				'reset_token' => null,
				'reset_token_expiration' => null,
			],
			[
				'nom' => 'Noel',
				'prenom' => 'Mathieu',
				'mail' => 'mathieu.noel@yahoo.fr',
				'mdp' => password_hash('MathieuNoel_56', PASSWORD_DEFAULT),
				'adresse' => json_encode(['query' => '22 rue Saint-Honoré 06000 Nice']),
				'tel' => '0612345678',
				'sexe' => 'H',
				'admin' => false,
				'age' => 40,
				'taille' => 175,
				'poids' => 78,
				'reset_token' => null,
				'reset_token_expiration' => null,
			],
			[
				'nom' => 'Durand',
				'prenom' => 'Elodie',
				'mail' => 'elodie.durand@hotmail.com',
				'mdp' => password_hash('Elod!e123', PASSWORD_DEFAULT),
				'adresse' => json_encode(['query' => '98 avenue du Stade 33000 Bordeaux']),
				'tel' => '0787654321',
				'sexe' => 'F',
				'admin' => false,
				'age' => 32,
				'taille' => 168,
				'poids' => 62,
				'reset_token' => null,
				'reset_token_expiration' => null,
			],
			[
				'nom' => 'Delaporte',
				'prenom' => 'Pierre',
				'mail' => 'pierre.delaporte@sfr.fr',
				'mdp' => password_hash('P!erre345', PASSWORD_DEFAULT),
				'adresse' => json_encode(['query' => '9 boulevard Leningrad 76600 Le Havre']),
				'tel' => '0786658313',
				'sexe' => 'H',
				'admin' => false,
				'age' => 25,
				'taille' => 188,
				'poids' => 92,
				'reset_token' => null,
				'reset_token_expiration' => null,
			],
		];

		$this->db->table('saiyan')->insertBatch($data);
	}
}
